Remove invalid no check and add open terminal

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,19 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-for arg in "$@"
-do
-    if [ "$arg" = "--nocheck" ]; then
-        echo "Skipping validation (--nocheck flag detected)"
-        exit 0
-    fi
-done
-
 echo "Running validations before commit..."
-./valid.bat
 
-if [ $? -ne 0 ]; then
-    echo "Validation failed! Commit aborted."
-    echo "To skip validation, use: git commit --nocheck"
-    exit 1
+./valid.bat
+STATUS=$?
+
+if [ $STATUS -ne 0 ]; then
+  echo "Validation failed! Commit aborted."
+  echo "To skip validation, use: git commit --no-verify -m 'Message' "
+  exit 1
 fi
